server:
  port: 9999
  tomcat:
    uri-encoding: utf-8
mybatis:
  type-aliases-package: com.github.ylfjm.**.po
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
mapper:
  identity: MYSQL
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
spring:
  profiles:
    active: dev
  application:
    name: ylfjm-server-cylinder
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location:
---
spring:
  profiles: dev
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3333/ylfjm-cyl?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
  servlet:
    multipart:
      location: D:/uploadFiles/
file:
  staticAccessPath: /static/uploadFiles/**
  resourceLocations: D:/uploadFiles/
---
spring:
  profiles: prod
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.10.64:3333/ylfjm-cyl?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
      username: ymkjdev
      password: EMallSleep!2019
file:
  staticAccessPath: /static/uploadFiles/**
  resourceLocations: /data/ylfjm/files/
