server:
  port: 9999
  tomcat:
    uri-encoding: utf-8
spring:
  application:
    name: ylfjm-server-cylinder
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3333/ylfjm-cyl?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
mybatis:
  type-aliases-package: com.github.ylfjm.**.po
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
mapper:
  identity: MYSQL
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql